export const skillLevels = [
    'Junior',
    'Señor',
    'Exhausted',
    'Uber-Experienced',
    'Top',
    'Superior',
    'Confident'
];

export const selfCompliments = [
    'Expert',
    'Grand Master',
    'Master',
    'Senior',
    'Ninja',
    'Masher',
    'Guardian',
    'Craftsman',
    'Brewer',
    'Lead',
    'Principal',
    'BDFL',
    'Magician',
    'Engineer',
    'Coder',
    'Craftswoman',
    'Sculptor',
    'Tech Manager',
    'Jedi',
    'Guru',
    'Hacker',
    'Craftsperson',
    'Champion',
    'Evangelist',
    'Advocate',
    'Pusher',
    'Sherpa',
    'Leader',
    'Captain',
    'Artist',
    'Director',
    'Artisan',
    'Keeper',
    'Evangelist',
    'Virtuoso',
    'Mentor'
];

export const topics = [
    'PHP',
    'Whisky', // hi mark
    'Java',
    'Android',
    'Keyboard',
    'Computers',
    'iOS',
    'Ruby on Rails',
    'SCRUM',
    'documenthypeWordHere',
    'Node.js',
    'Swift',
    'Pixel',
    'Full stack',
    'Scalable partnerships',
    'Developer Relations',
    'Haskell',
    'Erlang',
    'Cloud',
    'Satisfaction Design',
    'NoSQL',
    'Kanban',
    'Kotlin',
    'Creative Code',
    'Machine Learning',
    'Data Visualisation',
    'Big Data',
    'Reactive Programming',
    'Scala',
    'Agile'
];
